[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2.1.0"
csv = "1.2.1"
float-ord = "0.3.2"
serde = { version = "1.0.158", features = ["derive"] }
