name: Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: rustup toolchain install nightly --profile minimal --no-self-update
      - run: rustup default nightly
      - run: rustup component add rustfmt clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --all-features
      - run: cargo build --all-targets --all-features
      - run: cargo test --all-targets --all-features
